language: generic
services: docker
install:
  - |
    if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
      echo "$DOCKER_HUB_PASSWORD" | docker login --username stephanmisc --password-stdin
    fi
  - curl https://raw.githubusercontent.com/stepchowfun/bake/master/install.sh -LSfs | VERSION=0.15.0 sh
script:
  - |
    if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
      WRITE_REMOTE_CACHE=true
    else
      WRITE_REMOTE_CACHE=false
    fi
    bake \
      --repo stephanmisc/bake \
      --read-remote-cache true \
      --write-remote-cache "$WRITE_REMOTE_CACHE"
